name: rocket_todo
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  adaptive_dialog: ^1.8.0+1
  cupertino_icons: ^1.0.2
  drop_down_list: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.2
  path_provider: ^2.0.11
  sembast: ^3.3.1
  tap_debouncer: ^2.0.2

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  mockingjay: ^0.3.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/icon_android.png"
  image_path_ios: "assets/images/icon_ios.png"
